apiVersion: v1
kind: Service
metadata:
  name: {{ template "bk-hcm.fullname" . }}-agentserver
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  # StatefulSet 治理服务使用 Headless，保证 Pod 稳定网络标识与 PVC 绑定。
  clusterIP: None
  ports:
    {{- with .Values.agentserver.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    component: agentserver
