apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-hcm.fullname" . }}-apiserver-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |-
    network:
      bindIP:
      port: {{ .Values.apiserver.port}}
      tls:
        insecureSkipVerify: 
        certFile:
        keyFile:
        caFile:
        password:
    service:
      etcd:
        {{- include "common.tplvalues.render" (dict "value" (include "bk-hcm.etcdConfig" .) "context" $) | nindent 8 }}
    {{- with .Values.apiserver.mcp }}
    mcp:
      {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}
    {{- end }}
    {{- with .Values.apiserver.a2aPassthrough }}
    a2aPassthrough:
      {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}
    {{- end }}
    log:
      {{- toYaml .Values.apiserver.log | nindent 6 }}
    tenant:
      {{- toYaml .Values.tenant | nindent 6 }}
  {{- if and (not .Values.apiserver.disableJwt) .Values.apiserver.apigwPublicKey }}
  apigw_public.key: |-
      {{- .Values.apiserver.apigwPublicKey | b64dec | nindent 6 }}
  {{- end }}
  {{- if .Values.apiserver.mcp.internal.enable }}
  bk_apigw_resources_bk-hcm_internal_mcp.yaml: |-
    {{- .Files.Get "files/bk_apigw_resources_bk-hcm_internal_mcp.yaml" | nindent 4 }}
  {{- end }}
